version: '3.2'

services:
  db:
    image: mongo:4.0-rc-xenial
    environment:
      MONGO_INITDB_DATABASE: debug
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: debug
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
  web:
    build:
      context: .
      dockerfile: environments/flask-nginx/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./captaina:/app/captaina
      - ./config.py:/app/config.py
    environment:
      - FLASK_INSTANCE_PATH=/app/instance
      - STATIC_PATH=/app/captaina/static


  asr-master:
    restart: always
    build:
      context: .
      dockerfile: environments/asr-master/Dockerfile
    ports:
      - "5443:443"
    command: ["--port=443", "--block=True"]
    volumes:
      - ./kaldi-gstreamer-server:/opt/kaldi-gstreamer-server
      - ./captaina/models:/opt/kaldi-gstreamer-server/kaldigstserver/models

  asr-worker:
    restart: always
    build: 
      context: .
      dockerfile: environments/asr-worker/Dockerfile
    command: ["-c","/opt/asr-conf.yaml", "-u","ws://asr-master:443/worker/ws/speech"]
    volumes:
      - ./captaina/models:/opt/kaldi-gstreamer-server/kaldigstserver/models

  graph-creator:
    restart: always
    build: docker-online-kaldi/apps/graph-creator
    environment:
      - GRAPH_DIR=/opt/s5/data/mtlm-graphs
      - DICT_SRC=/opt/s5/data/local/dict
      - MODEL_DIR=/opt/s5/exp/chain/all_tdnn_9_b_online
      - SCALE_OPTS=--transition-scale 1.0 --self-loop-scale 1.0
      - CORRECT_BOOST=10.0

volumes:
  dbdata:
