version: '3.2'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: debug
      POSTGRES_DB: debug_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
