version: '3.2'

services:
  db:
    image: mongo:4.0-rc-xenial
    environment:
      MONGO_INITDB_DATABASE: debug
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: debug
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
